#!/usr/bin/env bash
# Generate poll/config.js from ../.env so the browser app gets its Supabase config
# without any keys being committed. config.js is gitignored.
#
# Run this before deploying the poll (e.g. `vercel deploy` from this dir, which
# includes the local config.js).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[ -f "$HERE/../.env" ] && { set -a; . "$HERE/../.env"; set +a; }

: "${SUPABASE_URL:?set SUPABASE_URL in ../.env}"
: "${SUPABASE_KEY:?set SUPABASE_KEY in ../.env}"

cat > "$HERE/config.js" <<EOF
// Generated by gen-config.sh from ../.env — do not commit (gitignored).
window.SODA_POLL_CONFIG = {
  supabaseUrl: "$SUPABASE_URL",
  supabaseKey: "$SUPABASE_KEY",
};
EOF

echo "Wrote $HERE/config.js"
